In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd
from eightd_evaluator import evaluate, classify_score

### 讀資料

In [2]:
# 評分標準
score_guide = pd.read_excel('data/8d_data.xlsx', sheet_name='評核標準')
score_guide.drop(columns='項目目的', inplace=True)
score_guide

,項目,評核標準
0,Cause of Occurrence,● 差劣 (0-5分)： 5W 條件（何時、何處、何事、何人、為何）僅包含 1 到 2 項，...
1,Correction Actions of Occurrence,● 差劣 (0-5分)： 未使用分析工具（如 5M1E），原因描述僅有 1 項且與現狀無關。...
2,Reason of Escape out,● 差劣 (0-5分)：\n1. 未依據前述已確認原因展開「流出原因」分析，或僅描述現象，未...
3,Correction Actions of Escape out,● 差劣 (0-5分)： 僅文字宣稱有效，無任何實質數據、照片或實驗結果支持。\n● 普通 ...
4,Prevention Actions,● 差劣 (0-5分)： 僅限於本案處理，未提及任何水平展開或預防其他料號的評估。\n● 普...
5,Standardization,● 差劣 (0-5分)： 沒有填寫文件名稱。 例如: '修订作业SOP'，這不是文件名，所以...

In [3]:
# 資料
report1 = pd.read_excel('data/8d_data.xlsx', sheet_name='8D報告內容')
report1

,項目,原始內容
0,Cause of Occurrence,經確認為供應商來料異常，在攻牙過程中，產品產生毛邊附著於螺紋上（因材質硬度較軟，攻牙時易產生...
1,Correction Actions of Occurrence,要求供應商明確區分良品與不良品區域，並將此類異常列為加工與出貨檢查重點，強化作業標準與人員訓練。
2,Reason of Escape out,1. 來料檢驗採用 AQL 0.25 抽樣標準，未能有效檢出微小螺紋缺陷。\n2. 檢驗SO...
3,Correction Actions of Escape out,修訂原物料IQC檢驗SOP，明確定義此類產品的檢驗重點、方法與判定基準。
4,Prevention Actions,1. 因來料採抽檢方式，且該類產品多數為客戶提供，導致內部對螺紋檢驗重視不足。\n2. 需建...
5,Standardization,1. 修訂IQC檢驗SOP，明確定義此類產品的檢驗重點與方法。\n2. 增設專用螺紋栓規檢測...

### 評分

In [4]:
# 欄位缺少
score_items = ['test']
print('欲評分欄位:', score_items)
evaluate(data=report1, guide=score_guide, check_item=score_items)

欲評分欄位: ['test']

AssertionError: 缺少欄位

In [23]:
# 欄位齊全
score_items = list(score_guide['項目'])
print('欲評分欄位:', score_items)
report1_scored = evaluate(data=report1, guide=score_guide, check_item=score_items)
report1_scored

欲評分欄位: ['Cause of Occurrence', 'Correction Actions of Occurrence', 'Reason of Escape out', 'Correction Actions of Escape out', 'Prevention Actions', 'Standardization']

,原始內容,score,reason,suggestion
項目,,,,
Cause of Occurrence,經確認為供應商來料異常，在攻牙過程中，產品產生毛邊附著於螺紋上（因材質硬度較軟，攻牙時易產生...,8,內容清晰地描述了「何事」（產品產生毛邊、供應商來料異常、作業人員未區隔導致不良品流入）、明確...,為了提升報告的完整性，建議補充以下資訊：\n1. **何時 (When):** 具體說明異...
Correction Actions of Occurrence,要求供應商明確區分良品與不良品區域，並將此類異常列為加工與出貨檢查重點，強化作業標準與人員訓練。,5,該糾正措施內容提出了一系列相關且合理的改善行動，涵蓋了區域區分、檢查重點、作業標準和人員訓練...,為了提升分數，建議在提出糾正措施之前，應先進行詳細的根本原因分析。明確說明：\n1. **...
Reason of Escape out,1. 來料檢驗採用 AQL 0.25 抽樣標準，未能有效檢出微小螺紋缺陷。\n2. 檢驗SO...,7,該內容清晰指出了兩項體系層面的問題：AQL 0.25 抽樣標準未能有效檢出微小螺紋缺陷，以及...,1. **應用分析工具：** 明確採用至少一種結構化分析工具（如魚骨圖或5M1E）來展開流出...
Correction Actions of Escape out,修訂原物料IQC檢驗SOP，明確定義此類產品的檢驗重點、方法與判定基準。,3,內容僅說明了對IQC檢驗SOP進行了修訂，並明確了檢驗重點、方法與判定基準，但未提供任何實質...,為證明修訂SOP的有效性，請提供以下佐證：\n1. 改善前後的IQC檢驗合格率、不良品發現率...
Prevention Actions,1. 因來料採抽檢方式，且該類產品多數為客戶提供，導致內部對螺紋檢驗重視不足。\n2. 需建...,12,內容明確指出問題根源 (客供物料與抽檢)，並提出建立「客戶提供物料」驗收風險評估機制的系統性...,1. 具體規劃「客戶提供物料」驗收風險評估機制的建立步驟、評估標準、責任單位及時程。 \n2...
Standardization,1. 修訂IQC檢驗SOP，明確定義此類產品的檢驗重點與方法。\n2. 增設專用螺紋栓規檢測...,1,內容中沒有明確填寫文件名稱。例如，'修訂IQC檢驗SOP' 中的 'IQC檢驗SOP' 只說...,請在描述中包含具體的文件名稱或文件編號。例如：修訂『IQC-2023-A01 產品A檢驗SO...

In [24]:
# 分類評分(差劣/普通/不錯/傑出)
report1_scored['score_level'] = report1_scored['score'].apply(classify_score)
display(report1_scored)

,原始內容,score,reason,suggestion,score_level
項目,,,,,
Cause of Occurrence,經確認為供應商來料異常，在攻牙過程中，產品產生毛邊附著於螺紋上（因材質硬度較軟，攻牙時易產生...,8,內容清晰地描述了「何事」（產品產生毛邊、供應商來料異常、作業人員未區隔導致不良品流入）、明確...,為了提升報告的完整性，建議補充以下資訊：\n1. **何時 (When):** 具體說明異...,普通
Correction Actions of Occurrence,要求供應商明確區分良品與不良品區域，並將此類異常列為加工與出貨檢查重點，強化作業標準與人員訓練。,5,該糾正措施內容提出了一系列相關且合理的改善行動，涵蓋了區域區分、檢查重點、作業標準和人員訓練...,為了提升分數，建議在提出糾正措施之前，應先進行詳細的根本原因分析。明確說明：\n1. **...,差劣
Reason of Escape out,1. 來料檢驗採用 AQL 0.25 抽樣標準，未能有效檢出微小螺紋缺陷。\n2. 檢驗SO...,7,該內容清晰指出了兩項體系層面的問題：AQL 0.25 抽樣標準未能有效檢出微小螺紋缺陷，以及...,1. **應用分析工具：** 明確採用至少一種結構化分析工具（如魚骨圖或5M1E）來展開流出...,普通
Correction Actions of Escape out,修訂原物料IQC檢驗SOP，明確定義此類產品的檢驗重點、方法與判定基準。,3,內容僅說明了對IQC檢驗SOP進行了修訂，並明確了檢驗重點、方法與判定基準，但未提供任何實質...,為證明修訂SOP的有效性，請提供以下佐證：\n1. 改善前後的IQC檢驗合格率、不良品發現率...,差劣
Prevention Actions,1. 因來料採抽檢方式，且該類產品多數為客戶提供，導致內部對螺紋檢驗重視不足。\n2. 需建...,12,內容明確指出問題根源 (客供物料與抽檢)，並提出建立「客戶提供物料」驗收風險評估機制的系統性...,1. 具體規劃「客戶提供物料」驗收風險評估機制的建立步驟、評估標準、責任單位及時程。 \n2...,不錯
Standardization,1. 修訂IQC檢驗SOP，明確定義此類產品的檢驗重點與方法。\n2. 增設專用螺紋栓規檢測...,1,內容中沒有明確填寫文件名稱。例如，'修訂IQC檢驗SOP' 中的 'IQC檢驗SOP' 只說...,請在描述中包含具體的文件名稱或文件編號。例如：修訂『IQC-2023-A01 產品A檢驗SO...,差劣

### 存檔

In [25]:
report1_scored.to_excel('data/scored_report.xlsx')